### ISSUE TITLE
Display the current profile details above the wizzard

### ISSUE THREAD

**Issue by rstavro** [xwikisas/application-confluence-migrator#14]
Above the wizzard, add the details of the active profile :
- link / button to edit the profile
- space name with a link to the Confluence space (computed from the URL and the space name provided in the active profile)

**Comment by acotiuga** [comment]
Before:
![before](https://user-images.githubusercontent.com/8121819/121874981-9b15cc80-cd10-11eb-83f9-d3b7bf0af40f.png)

After:
![after](https://user-images.githubusercontent.com/8121819/121874992-9d782680-cd10-11eb-8b6e-708bc5af5c2b.png)
