### ISSUE TITLE
Create the Confluence Migration form

### ISSUE THREAD

**Issue by rstavro** [xwikisas/application-confluence-migrator#2]
The Confluence Import form should be similar to the Filter Stream form, but simplified, displaying only the configurable fields (removing the fields that have no value / constant value), with the goal to improve the user experience for the imports.

**Comment by tmortagne** [comment]
Maybe even make it a wizard ?

**Comment by rstavro** [comment]
That sounds very good ! Would it be possible / easy to reuse the code of the Distribution Wizard UI ? I never tried that before.

**Comment by tmortagne** [comment]
I think the DW code is too DW specific.

**Comment by rstavro** [comment]
Ok. That answers my question :) Thanks, Thomas ! I will look for solutions and I will decide afterwards on what would be the best approach.
