### ISSUE TITLE
Change text on Home page of the Migrator

### ISSUE THREAD

**Issue by ldubost** [xwikisas/application-confluence-migrator#21]
Add at the beginning:

"Welcome to the Confluence Migrator. This tool will help you import the content from your Confluence instance to XWiki. For more information about this tool and pre-requisite about the Confluence Import please visit the [[Confluence Migrator documentation>>url:<linktostore>"

And change this text from:

"A migration profile is defined by the data about authentication, the Confluence instance URL and the space to be migrated. The status of the migration is stored into the profile so that the migration can resumed at any step."

to

"A migration profile represents the migration of a Confluence space to XWiki. In a migration profile you will provide information about the Confluence instance and space including authentication credentials which will allow to analyze your instance. The profile will also track your progress through the import in order to be able to resume your import at any step"

**Comment by acotiuga** [comment]
![intro](https://user-images.githubusercontent.com/8121819/125642873-983bb711-18ec-49ee-883d-4db74dfa5f73.png)

**Comment by acotiuga** [comment]
![introWithProfile](https://user-images.githubusercontent.com/8121819/125644068-649e9f21-f1c7-4705-9d7f-9c97b98401db.png)
