### ISSUE TITLE
Modify Nested Pages Migrator to include the pageLength size check

### ISSUE THREAD

**Issue by ldubost** [xwikisas/application-confluence-migrator#23]
We need to created a ticket and release a new version of the nested pages migrator to:

1/ Include the size check change by default

"(254 - XWiki.currentWiki.length)"

2/ Modify the maximum size (768) for more recent version of XWiki (13.2+) following https://jira.xwiki.org/browse/XWIKI-18429

**Comment by acotiuga** [comment]
This need is described in https://jira.xwiki.org/browse/NPMIG-56
