### ISSUE TITLE
Wrong display on migrator page

### ISSUE THREAD

**Issue by ldubost** [xwikisas/application-confluence-migrator#24]
When creating a profile and then clicking on start migration the following is displayed:

![image](https://user-images.githubusercontent.com/652233/125616123-b9d07c65-cd21-484b-814e-3932dfef2d88.png)

**Comment by ldubost** [comment]
It seems this error does not display if the Confluence URL is complete.
With https://xwikisas.atlassian.net/ there is the display error (+ edit link seems invalid)
With https://xwikisas.atlassian.net/wiki the display is correct and edit link works

**Comment by acotiuga** [comment]
@ldubost maybe your dealing with an old version of the code, I cannot reproduce the issue.
