### ISSUE TITLE
Confluence Space Analysis error handling

### ISSUE THREAD

**Issue by ldubost** [xwikisas/application-confluence-migrator#28]
We would need a connection test to verify the settings provided on the Configuration screen.
The URL setting shoud document that the URL needs to include a path.. For example for cloud it's

https://<mywikiname>.atlassian.net/wiki

**Comment by acotiuga** [comment]
Profile page - Failing connection message and stacktrace:
![error](https://user-images.githubusercontent.com/8121819/135883002-dc2eeddb-eab9-4589-9ee7-1ea78aff7384.png)

Profile page - Succeeded connection message:
![success](https://user-images.githubusercontent.com/8121819/135883008-c7a4c047-7f1b-4a1b-8331-85fcfd981269.png)

Job - Failing connection message:
![errorJob](https://user-images.githubusercontent.com/8121819/135883417-a8019bf3-ee06-42a0-86f2-3f55970d0357.png)

Job - Succeeded connection message:
![sucessJob](https://user-images.githubusercontent.com/8121819/135883010-a0076c2b-6e8c-42ea-809e-42a1a0e09e13.png)
