### ISSUE TITLE
Confluence XML Export Import - Attach file and find url for source

### ISSUE THREAD

**Issue by ldubost** [xwikisas/application-confluence-migrator#32]
We should provide a place to

1/ upload the file for imports of less than 1Gb and then generated the URL using
https://snippets.xwiki.org/xwiki/bin/view/Extension/Find%20the%20filesystem%20location%20of%20an%20attachment/

2/ Explain how to upload your file to your server and how to generate the URL for import

This would simplify the import process

**Comment by acotiuga** [comment]
Provide an upload form to load the zip file in the Migration homepage doc the file path on the file store
Remove the attachment from the document, after the path is obtained
Update the source input with the file path
Hide the source input from the filter form (as it is auto-filled)

Results:
![1](https://user-images.githubusercontent.com/8121819/139629102-7fa211e9-39e2-429a-96b4-6bba1f743a0e.png)
![2](https://user-images.githubusercontent.com/8121819/139629108-36557aa2-e91e-484e-bea9-b5d45885ff1d.png)
![3](https://user-images.githubusercontent.com/8121819/139629113-f3a2f018-acbb-4ea1-96f8-eb1688d12717.png)
