### ISSUE TITLE
Add finished state to the migration profile

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator#49]
Currently, a user is able to start the migration profile and carry the migration, but after clicking on "Finish", the migrator doesn't change its state. Moreover, the user is only able to open a new migration profile if they restart the current profile. The restart of the current profile erases the imported pages. As the users will need to migrate multiple spaces, we need to add the option to create and finish multiple migration profiles (for each space) and keep the previously imported pages when opening a new migration.

Requirements: 

1. Please add a finished state to the profiles. If the profile is in this state, the user is not able to edit it anymore, and the imported pages are kept.

2. Please add, on the Profiles page, an option to create a new migration profile. This option should be valid only if no other profile is active (in progress).

**Comment by acotiuga** [comment]
At this point, there is no need to have a state on the profiles, so only nr 2. is implemented.
