### ISSUE TITLE
Warn users that nested pages migrator 0.8.x is incompatible

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator#67]
The Confluence migrator currently works with Nested Pages Migrator 0.7.3 as a dependency. If the Nested Pages Migrator is upgraded to 0.8.x, step 6 (nested pages migration) of the confluence migrator fails. 

If the users upgrade their Nested Pages Migrator application to 0.8.x and then use the Confluence Migrator, at step 6 we should display a warning message that instructs the user to downgrade their Nested Pages Migrator application back to 0.7.x.

**Comment by ldubost** [comment]
Fixed using a warning
