### ISSUE TITLE
Step 1 : Prerequisites

### ISSUE THREAD

**Issue by rstavro** [xwikisas/application-confluence-migrator#7]
This step should list the requirements for migrations to be possible. It should list the following needs:
- memory / cache
- heavy processes to be disabled
- extensions to be installed

Some of the values could be computed. Check if / how this can be done and decide on what recommendations and how to display them, based on these values.

See more details on the [specifications page](https://projects.xwikisas.com/xwiki/bin/view/Projects/XWikiSAS/Confluence%20Tools%20and%20Services/ConfluenceImporterSpecifications/#HTab1:XWikiPrerequisites).

**Comment by acotiuga** [comment]
Further improvements to be done as part of #18.
