### ISSUE TITLE
Confluence migration fails from subwikis

### ISSUE THREAD

**Issue by js-ddev** [xwikisas/application-confluence-migrator#74]
The migrator extension can be installed flawlessly on a sub-wiki, yet at step 1 there is a velocity error.

It seems the page reference used by the migrator can only be on a main wiki.

Here are some samples of the error:

`Caused by: org.xwiki.velocity.XWikiVelocityException: Failed to evaluate content with namespace [subwikiid:Confluence.Migrator.Code.MigratorSheet]`

`Caused by: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'resetMigration' in class com.xwiki.confluencemigrator.script.ConfluenceMigratorProfileScriptService threw exception java.lang.NullPointerException at subwikiid:Confluence.Migrator.Code.MigratorSheet[line 18, column 55]`

**Comment by ClemensRobbenhaar** [comment]
PR at https://github.com/xwikisas/application-confluence-migrator/pull/78
