### ISSUE TITLE
Nested pages migrator step 6 not working on XWiki 14+

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator#76]
The 6th step of the confluence migrator includes the nested pages migrator, version 0.7.3. 

On 14.0 the nested pages migrator step works as expected, but starting with 14.1. the plan is not computed and it is not possible to migrate the pages to their correct hierarchy. 

Steps: 
1. Setup a 14.0 and a 14.1 xwiki instance
2. Install the Confluence Migrator (with nested pages migrator 0.7.3. as a dependency)
3. Run a migration 
4. At the last step of the migrator click on compute plan

Expected: The plan is computed and the proposed hierarchy is shown. The user has the option to tick/untick certain nodes and execute the plan. The behavior is as expected for XWiki <= 14.0

Actual: For 14+, the plan is not computed, the "There is nothing to do" message appears and the hierarchy only shows "Preferences" and "Right"

**13.10.4 zip, flavor preinstalled**
![13 10 4 -flavor-zip-nested-0 7 3](https://user-images.githubusercontent.com/35834028/194596515-a5076b88-9afa-4211-9f8c-ade1b97bccee.png)

**14.0 zip, flavor preinstalled** 
![14 0-flavor-zip-nested-0 7 3](https://user-images.githubusercontent.com/35834028/194596525-290451e7-9eb7-4032-a341-28c7774a93d2.png)

**14.1 zip, flavor preinstalled**
![14 1-flavor-zip-nested-0 7 3](https://user-images.githubusercontent.com/35834028/194596717-82e21942-5d99-4d18-8cc8-54bb17ce2313.png)

**14.4 zip, flavor preinstalled**
![14 4-flavor-zip-nested-0 7 3](https://user-images.githubusercontent.com/35834028/194596544-c3f8cca2-33cb-4548-bce4-54872b4c438c.png)

**14.4.3 cloud demo** 
<img width="1391" alt="14 4 3-cloud-nested-0 7 3" src="https://user-images.githubusercontent.com/35834028/194596554-2aedfa9c-f5a0-4089-b824-9d62866a2f45.png">

**14.6 zip flavor preinstalled**
![14 6-flavor-zip-nested-0 7 3](https://user-images.githubusercontent.com/35834028/194596589-35275a03-9c8d-4ad6-be39-58aa98a9f38b.png)

**Comment by ClemensRobbenhaar** [comment]
As it turns out, this is the same as [NPMIG-60](https://jira.xwiki.org/browse/NPMIG-60), just with a piece of code that has been copied over completely from the nested pages migrator app.
