### ISSUE TITLE
Style is lost from time to time on the migrator

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator#84]
Steps to reproduce: 
1. Create a migration profile 
2. Refresh the migration page once or a few times

Expected: the style of the migrator is loaded after each refresh
Actual result: the style of the migrator is not loaded upon some refreshes. 

Correct style: 
<img width="1152" alt="Screenshot 2022-10-26 at 19 32 23" src="https://user-images.githubusercontent.com/35834028/198083119-3b2851b6-4b2c-43a5-ac4e-03f471bc53a3.png">

Missing style:
<img width="1440" alt="Screenshot 2022-10-26 at 19 32 10" src="https://user-images.githubusercontent.com/35834028/198083429-eb8a9a1c-ef19-4f37-b9b3-f7d9b283de31.png">

**Comment by snazare** [comment]
reproduced on XWiki 14.4.3 cloud and XWiki 14.6 local jetty, chrome 106.0.5249.61, macos 12.5.1

**Comment by mouhb** [comment]
I noticed that the Nested [Pages Migrator application](https://github.com/xwiki-contrib/application-nestedpagesmigrator/) is also affected by this issue. It seems that there is a change on the XWiki platform (14.1+) that is causing the issue.

**Comment by mouhb** [comment]
Note that the issue do not appears on recent versions of the "Nested Pages Migrator".
