### ISSUE TITLE
Upgrade dependencies used by the migrator

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator#90]
Please upgrade the Confluence Syntax, Confluence XML and XHTML Syntax to 9.16.0. 

The migrator is currently using 9.15.3 Confluence Syntax, Confluence XML and XHTML Syntax, but the latest version 9.16.1 brings [important improvements](https://extensions.xwiki.org/xwiki/bin/view/Extension/Confluence/#H9.16.1).

**Comment by acotiuga** [comment]
This is fixed in https://github.com/xwikisas/application-confluence-migrator/commit/8c77bf2fdb89cd1cc86d273e31b730ad5c103662.
